# -*- coding: utf-8 -*-
"""List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GReGstW8B7vWUDXnaflx2Gb7It96L5BF
"""

# Print positive and negative elements of an List?
# Mean of List elements?
# Find the greatest element and print its index too?
# Find the second greatest element?
# Check if List is sorted or not.

nums = [24,13,67,-98,0,-54]
positive = []
negative = []

for n in nums:
  if n > 0:
    positive.append(n)
  else:
    negative.append(n)

print(positive)

# Mean of List elements?

nums = [23,14,13,56,78]
sum = 0
count = 0

for n in nums :
  sum = sum + n
  count = count + 1

print(sum/count)

## Find the greatest element and print its index too?
nums = [34,56,45,25,99]
largest = nums[0]
index = 0

for n in nums :
  if n > largest :
    largest = n
    index = nums.index(n)

print(largest)
print(index)

# Find the second greatest element?

nums = [34,56,45,25,99]
sec_largest = nums[1]
largest = nums[0]

for n in nums:
  if n > largest:
    sec_largest = largest
    largest = n
  elif n > sec_largest:
    sec_largest = n

print(sec_largest)

# Check if List is sorted or not.

nums = [34,56,45,25,99]

for n in range(len(nums)-1):
  if nums[n] > nums[n+1]:
    continue
  else :
    print("Not sorted")
    break
else:
  print("Sorted")

